=head1 NAME

ProductNews - Show news about the product on the Dashboard

=head1 DESCRIPTION

If you have news about your product or any other message that all agents of your
OTRS system should know about, you can use ProductNews to handle this.

With this extension a new dashboard widget is created and administrators can add
news.

As of version 4.0.4, all users can create news and admin and the news author can
edit them. Now it is possible to show news in other views as well: AgentTicketZoom,
AgentTicketPhone, AgentTicketEmail.

=head1 REPOSITORY AND BUGTRACKER

The code repository and a bugtracker is available at L<http://github.com/reneeb/otrs-ProductNews>.

=head1 CONTRIBUTORS

Torsten Thau, c.a.p.e IT (L<http://cape-it.de>)

 * Made it ready for OTRS 3.3
 * Inlineediting

Oberender Frank, c.a.p.e IT (L<http://cape-it.de>)

 * visbility in Customer-Frontend and on Login-Screens

Never Min, znuny (L<http://znuny.cn>)

 * Chinese translation

Balázs Úr, OTRS-megoldások (L<http://www.otrs-megoldasok.hu>)

 * Hungarian translation

=head1 AUTHOR AND LICENSE

Renee Baecker, L<http://perl-services.de>

This software comes with ABSOLUTELY NO WARRANTY. 
For details, see the enclosed file COPYING for 
license information (AGPL). If you did not receive 
this file, see L<http://www.gnu.org/licenses/agpl.txt>.
